# Generated by Django 4.2.4 on 2023-08-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='맛집 이름')),
                ('score', models.FloatField(default=0, verbose_name='평점')),
                ('latitude', models.CharField(max_length=20, verbose_name='위도')),
                ('longitude', models.CharField(max_length=20, verbose_name='경도')),
                ('tag', models.CharField(max_length=100, verbose_name='태그')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.nation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
